import { Fa500Px, FaBehance, FaBlogger, FaDribbble, FaEnvelope, FaFacebook, FaFlickr, FaGithub, FaGlobe, FaInstagram, FaLinkedin, FaMapMarker, FaMedium, FaPhone, FaPinterest, FaReddit, FaSnapchat, FaSoundcloud, FaSpotify, FaTiktok, FaTwitter, FaVimeo, FaYoutube } from "react-icons/fa";

// make an array with social links  and add the id to each link
export const SocialLinks = [
  {
    id: 'facebook',
    title: 'Facebook',
    url: 'https://facebook.com/',
    hasUrl: true,
    background: '#3b5998',
    icon: <FaFacebook size={24} />,
    isSocialNetowrk: true,
    type: 'social-network',
    isPopular: true,
  },
  {
    id: 'twitter',
    title: 'Twitter',
    background: '#1da1f2',
    url: 'https://twitter.com/',
    hasUrl: true,
    icon: <FaTwitter size={24} />,
    isSocialNetowrk: true,
    type: 'social-network',
    isPopular: true,
  },
  {
    id: 'instagram',
    title: 'Instagram',
    background: '#e1306c',
    url: 'https://instagram.com/',
    hasUrl: true,
    icon: <FaInstagram size={24} />,
    isSocialNetowrk: true,
    type: 'social-network',
    isPopular: true,
  },
  {
    id: 'tiktok',
    title: 'Tiktok',
    background: '#4e2a84',
    url: 'https://tiktok.com/',
    hasUrl: true,
    icon: <FaTiktok size={24} />,
    isSocialNetowrk: true,
    type: 'social-network',
    isPopular: false,
  },
  {
    id: 'reddit',
    title: 'Reddit',
    background: '#ff4500',
    url: 'https://reddit.com/',
    hasUrl: true,
    icon: <FaReddit size={24} />,
    isSocialNetowrk: true,
    type: 'social-network',
    isPopular: false,
  },
  {
    id: 'youtube',
    title: 'Youtube',
    background: '#ff0000',
    url: 'https://youtube.com/',
    hasUrl: true,
    icon: <FaYoutube size={24} />,
    isSocialNetowrk: true,
    type: 'video',
    isPopular: false,
  },
  {
    id: 'linkedin',
    title: 'Linkedin',
    background: '#0077b5',
    url: 'https://linkedin.com/',
    hasUrl: true,
    icon: <FaLinkedin size={24} />,
    isSocialNetowrk: true,
    type: 'social-network',
    isPopular: false,
  },
  {
    id: 'github',
    title: 'Github',
    background: '#000000',
    url: 'https://github.com/',
    hasUrl: true,
    icon: <FaGithub size={24} />,
    isSocialNetowrk: false,
    type: 'dev',
    isPopular: false,
  },
  {
    id: 'medium',
    title: 'Medium',
    background: '#000000',
    url: 'https://medium.com/',
    hasUrl: true,
    icon: <FaMedium size={24} />,
    isSocialNetowrk: false,
    type: 'blog',
    isPopular: false,
  },
  {
    id: 'pinterest',
    title: 'Pinterest',
    background: '#cb2027',
    url: 'https://pinterest.com/',
    hasUrl: true,
    icon: <FaPinterest size={24} />,
    isSocialNetowrk: true,
    type: 'social-network',
    isPopular: false,
  },
  {
    id: 'snapchat',
    title: 'Snapchat',
    background: '#fffc00',
    hasUrl: false,
    icon: <FaSnapchat size={24} />,
    isSocialNetowrk: true,
    type: 'social-network',
    isPopular: false,
  },
  {
    id: 'spotify',
    title: 'Spotify',
    background: '#1db954',
    url: 'https://spotify.com/',
    hasUrl: true,
    icon: <FaSpotify size={24} />,
    isSocialNetowrk: false,
    type: 'music',
    isPopular: false,
  },
  {
    id: 'soundcloud',
    title: 'Soundcloud',
    background: '#ff5500',
    url: 'https://soundcloud.com/',
    hasUrl: true,
    icon: <FaSoundcloud size={24} />,
    isSocialNetowrk: false,
    type: 'music',
    isPopular: false,
  },
  {
    id: 'vimeo',
    title: 'Vimeo',
    background: '#1ab7ea',
    url: 'https://vimeo.com/',
    hasUrl: true,
    icon: <FaVimeo size={24} />,
    isSocialNetowrk: false,
    type: 'video',
    isPopular: false,
  },
  {
    id: 'behance',
    title: 'Behance',
    background: '#1769ff',
    url: 'https://behance.com/',
    hasUrl: true,
    icon: <FaBehance size={24} />,
    isSocialNetowrk: false,
    type: 'desing',
    isPopular: false,
  },
  {
    id: 'dribbble',
    title: 'Dribbble',
    background: '#ea4c89',
    url: 'https://dribbble.com/',
    hasUrl: true,
    icon: <FaDribbble size={24} />,
    isSocialNetowrk: false,
    type: 'desing',
    isPopular: false,
  },
  {
    id: 'flickr',
    title: 'Flickr',
    background: '#ff0084',
    url: 'https://flickr.com/',
    hasUrl: true,
    icon: <FaFlickr size={24} />,
    isSocialNetowrk: false,
    type: 'photo',
    isPopular: false,
  },
  {
    id: '500px',
    title: '500px',
    background: '#000000',
    url: 'https://500px.com/',
    hasUrl: true,
    icon: <Fa500Px size={24} />,
    isSocialNetowrk: false,
    type: 'photo',
    isPopular: false,
  },
  {
    id: 'blogger',
    title: 'Blogger',
    background: '#f57d00',
    url: 'https://blogger.com/',
    hasUrl: true,
    icon: <FaBlogger size={24} />,
    isSocialNetowrk: false,
    type: 'blog'
  },
  {
    id: 'phone',
    title: 'Phone',
    background: '#000000',
    hasUrl: false,
    icon: <FaPhone size={24} />,
    isSocialNetowrk: false,
    type: 'contact',
    isPopular: true,
  },
  {
    id: 'email',
    title: 'Email',
    background: '#000000',
    hasUrl: false,
    icon: <FaEnvelope size={24} />,
    isSocialNetowrk: false,
    type: 'contact',
    isPopular: true,
  },
  {
    id: 'address',
    title: 'Address',
    background: '#000000',
    hasUrl: false,
    icon: <FaMapMarker size={24} />,
    isSocialNetowrk: false,
    type: 'contact',
    isPopular: true,
  },
  {
    id: 'website',
    title: 'Website',
    background: '#000000',
    hasUrl: false,
    icon: <FaGlobe size={24} />,
    isSocialNetowrk: false,
    type: 'contact',
    isPopular: true,
  },
]
